Update requirements.txt
ccxt==1.87.48 cause deployment issue with the below error in google cloud function:
ERROR: No matching distribution found for ccxt==1.87.48; Error ID: c84b3231 

I updated requirement.txt with cctx:2.6.22 and deployed it successfully.